import img_p from "../../assets/images/sing.png";

const contents = {
  content: [
    {
      title: "Співай 1",
      link: "../",
      text: "Американський 3D комп'ютерно-анімаційний музично-комедійний фільм, знятий Гартом Дженнінгсом. Прем'єра стрічки в Україні відбулась 29 грудня 2016 року. Фільм розповідає про коалу Бастера, який організовує пісенний конкурс.",
      category: "Мультфільм",
      time: "110хв",
      rating: "7.1",
      promo_img: img_p,
      delete_icon: true,
      like: 126,
      dislike: 2,
      links_icon: true,
      netflix_link: "../",
      megogo_link: "../",
      move_icon: true,
      add_top: false,
      add_wishlist: false,
    },
    {
      title: "Співай 2",
      link: "../",
      text: "Анімаційний фільм «Співай 2» від студії Illumination Entertainment випускає компанія Universal Pictures. Це продовження однойменного мультфільму, що вийшов на екрани у 2016 році. Проект став першим у світі анімаційним мюзиклом. Герої переспівали близько 30 всесвітньо-відомих хітів. Ці пісні у виконанні тварин, тобто акторів, які їх озвучували, тривалий час трималися у різних хіт-парадах світу. При затратах на виробництво у 75 млн доларів мультфільм зібрав у світовому прокаті близько 635 млн доларів. Про роботу над продовженням оголосили у 2017 році.",
      category: "Мультфільм",
      time: "110хв",
      rating: "7.1",
      promo_img: img_p,
      delete_icon: true,
      like: 126,
      dislike: 2,
      links_icon: true,
      netflix_link: "../",
      megogo_link: "../",
      move_icon: false,
      add_top: true,
      add_wishlist: false,
    },
    {
      title: "Співай 3",
      link: "../",
      text: "Американський 3D комп'ютерно-анімаційний музично-комедійний фільм, знятий Гартом Дженнінгсом. Прем'єра стрічки в Україні відбулась 29 грудня 2016 року. Фільм розповідає про коалу Бастера, який організовує пісенний конкурс.",
      category: "Мультфільм",
      time: "123хв",
      rating: "7.4",
      promo_img: img_p,
      delete_icon: false,
      like: 127,
      dislike: 4,
      links_icon: false,
      netflix_link: "../",
      megogo_link: "../",
      move_icon: false,
      add_top: false,
      add_wishlist: true,
    },
  ],
};
export default contents;
